#------------------------------------------------------------------------------#

TEX_FILES := $(shell find -maxdepth 1 -name '*.tex' -type f -exec basename {} \;)
EXT_FILES := $(shell find -maxdepth 2 \
             -name '*.cls' -or \
             -name '*.sty' -or \
             -name '*.bib' -or \
             -name '*.asy')

PDF_FILES := $(TEX_FILES:.tex=.pdf)

LATEX := >/dev/null 2>&1 latexmk -pdf -silent

PRINT_LOG = texlogfilter --filename $(@:.pdf=.log)

ASY_DONE := ./asy/_all_done
MAKE = make --no-print-directory -C 

DEPENDENCIES := $(EXT_FILES) $(wildcard ./figs/*) $(ASY_DONE)

#------------------------------------------------------------------------------#

all: $(PDF_FILES)

%.pdf: %.tex $(DEPENDENCIES)
	@ echo Compiling $@
	@ $(LATEX) || $(PRINT_LOG)

$(ASY_DONE):
	@ $(MAKE) asy

#------------------------------------------------------------------------------#

.PHONY: clean
clean:
	@ echo Cleaning $(notdir $(CURDIR))
	@ $(MAKE) asy clean
	@ rm -f *~ .*~ *.bak                                    \
          *.aux *.bbl *.blg *.lof *.log *.lot *.out *.toc \
          *.bcf *.run.xml *.snm *.nav *.vrb .*.sw?        \
          *.psynctex.gz *.synctex.gz *.rubbercache *.pre  \
          *.fdb_latexmk *.fls *.dvi

.PHONY: distclean
distclean: clean
	@ echo Distcleaning $(notdir $(CURDIR))
	@ $(MAKE) asy distclean
	@ rm -f *.pdf

#------------------------------------------------------------------------------#
